baseURL = "https://cos-static-web-hosting-public-bucket.s3-web.eu-de.cloud-object-storage.appdomain.cloud/"
contentdir    = "content"
languageCode = "en-us"
title = "Sebastian Sprenz"
theme = "paperback"
disableKinds = ["section", "taxonomy", "term", "RSS"]

[params]
  mainSections = ["post"]
